; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 
	115200
	
build_flags =
	-I App/Core/inc
	-I App/Drivers/inc
	-I App/Services/inc
	-I App/Tasks/inc
	-D CORE_DEBUG_LEVEL=3

# Фильтр исходников: собираем всё в src и всё в App
# build_src_filter = +<*> +<../App/**/*.cpp> +<../App/**/*.c>

build_src_filter = 
    +<*> 
    +<../App/Core/src/>
    +<../App/Drivers/src/>
    +<../App/Services/src/>
    +<../App/Tasks/src/>


# Принудительное сканирование зависимостей (Fix для WiFi.h)
lib_ldf_mode = deep+

# Явно просим PIO включить библиотеку WiFi из фреймворка
lib_deps = WiFi
		WebServer


